[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "416c995726fc4fc864bfc3aa081438122f4df79b"
os = "macos"

    [[Cairo.download]]
    sha256 = "535b1416c8dcbb29dfc0585537330525c943814f9b92fbc91a866bfffc75694c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.x86_64-apple-darwin14.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "b0b93a52c4d5d445fddd76fe7f9a6c75c5c7627c"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "b4ecef5d24ceb94d3361f430c5d79685808d7a3fa97f87550708713faa706953"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.i686-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "4124571ef77c1ff5de6bc9cd751634cba3fd2aa2"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "41402c17b33148a79d8043aecc9e6217a33c8aed85128bdaa8fb7e03c476a599"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Cairo]]
arch = "powerpc64le"
git-tree-sha1 = "d990bd646f8f32d922593b77c2b36f07aa028d2d"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "31179171578460dd13bd37af4beaf23c7322a57713f75c6f7d8cd28b2cade527"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "27033d15a046c5e1332ac8fd4dcddf4521e5a7dd"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "a180b188eea25a587858f05281314e53c4d55d81acc7d96e4b5423903109db39"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.x86_64-linux-musl.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "8b005f0c8af1c160abad50551b82e31ba6ab9a2e"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "9ec0217cb02a5a47cdb4c47f363867336056cf4f75ae80c290a00c04bbaa9061"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.x86_64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "afbd988af164f8ea15dddd0a244cf24b9518db5e"
os = "windows"

    [[Cairo.download]]
    sha256 = "71f01f207ac0c46497aa2c9f6461d84ccb211b262324d63a8079cd5e6959f844"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.x86_64-w64-mingw32.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "b051560fb3213b29ae9aec3ea9ccae621b24999a"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "8b9992aa8e28afd58d21a884a8cf54f3d4be2430f2ddf1750dd6e084b08a31bf"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.aarch64-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "4be97cd6a28250808dfcf939eae7153a7c8912b9"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "c3f1f5ebe7f20582374fc242aaacce69f7a8ceba4b9ed1d4d174d5a95449c9a0"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.arm-linux-gnueabihf.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "08cf8ef4e08aa22f773af2c63ec821cb47eb956f"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "35084c8030492a0a56213ea62c61682d215853213dde1c6c6e48c50237156c8b"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.i686-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "b34f589cb23fa3e8b3ea7ea5b90f690612bf72f4"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "3a3e1ce4968a297f64cb84ce39900a9fe11404f228fe71a43f52d7f8d9adc71a"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.arm-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "de654f8e1d26fa9c964b354043779b8ff691f4b9"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "3453fad6bac961b37d05e4660bf2da50831529909f068611f109938be688fda1"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.aarch64-linux-gnu.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "bf74da2ba3f5d76b77ee77104048101081c5d534"
os = "windows"

    [[Cairo.download]]
    sha256 = "c2cccb160f734d2207f4a62ae3411fbb351be61aa5880be2ba803590b0062a18"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+0/Cairo.v1.16.0.i686-w64-mingw32.tar.gz"
