[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "58d063b7bb875334cf5ad586d914ecc73d8f597b"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "72313d3b4d1270194a32d6143b2989abf687e333555c06a8b8fae98a1d3c68b2"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.x86_64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "d164b6ba88dc391c90c8fedfc4138f59b1aa7e39"
os = "macos"

    [[Cairo.download]]
    sha256 = "0d164d866c6c07571fd9055683e2c4b797a76d950a5805e6e0bc2dc2d435c8a8"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.x86_64-apple-darwin14.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "7548fee5e40ef107029483ef4cc06bb773acbd5f"
os = "windows"

    [[Cairo.download]]
    sha256 = "71343fb37b79e24e08febbc499f6b51fa6106ba8cdab59cff965e83692c06714"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.i686-w64-mingw32.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "e77dafc25e58fd4a67e32fa284a150a608ff0db3"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "75c2c3dde207079c1acab80303f601355841ee476abd72b0d59b86b3933d96ad"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.aarch64-linux-gnu.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "d5707dd4ba8735dc8199dc7191d3e3a525cb0ef9"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "d14ed4f15d917e7f7878bd79ba8486bf38c11437747b2cccc98a0be4d140af6d"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.i686-linux-musl.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "18b41cdbde573cc1c1af747aaef885ceffa50272"
os = "windows"

    [[Cairo.download]]
    sha256 = "59d7012121963bb17d1f625789abf7fd499551872661ba226b78021240065783"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.x86_64-w64-mingw32.tar.gz"
[[Cairo]]
arch = "powerpc64le"
git-tree-sha1 = "6aac667d54b6920632cad1b7cf76a4cebfb75e03"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "76139f8fef17cde05da5892ee8e3f10477ae965bf1dd632decb5b61a74e5a8c9"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.powerpc64le-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "ebe8f53263ad52e753d04b64ae40836eb2752bd8"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "d618ebc00b30b38b6cb5c48d18a7f20bef2094d1ccbadec7f64544f195bb893c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.x86_64-unknown-freebsd11.1.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "d240a6550f0efe5fe99f172bfee2f03a3df7ffe0"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "2d37b8994788fcf806ba4ef432af84d68e1384d8bc6aa3803127458f53e9b886"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.arm-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "9bffbc0000fcf3a596757719dc84535dd8ba53b1"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "7da9585118ab60bf9406819e6d71b283ed3112c0851dceaa40771f703a11c2a7"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.aarch64-linux-musl.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "a2b1deb2ec09bde9bcb5d17b2b246ddd1c3a270c"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "8d9cbddfefce4b17434b5717037b2210fe63e1a108c00f166697eda99f0e5c07"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.i686-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "183458571507760ce52690c4ee2951418b115fcf"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "e0bc8c88a691f86845d5b64e74d3e069213cc0cd3809503803c5b43c165b544c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.x86_64-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "c58e16d1596a11b4aef3e7860b1081a6af0ce481"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "2247c3cc3cd8c64ee24fea7b96f6326c6eab12a2ffdbdaf150959a63ba6b9a3c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.14.12+0/Cairo.v1.14.12.arm-linux-gnueabihf.tar.gz"
