[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "eeb96836545753655e515a8080d6e1c1de9a763a"
os = "macos"

    [[Cairo.download]]
    sha256 = "fbb3c311d23ccb800a1b18355fbf52328e90769e45550df98bd78342ef650f6c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.x86_64-apple-darwin14.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "aaf1faa531261ebce1da3fa118ff4bdf2dcdcadc"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "73bf7f7f1c2cbac14f74e16f201b963a8158aa69e797977a3cd3e5633a8281ee"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.i686-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "2d8dfe131fc90c83d13be8a5d9f4a5e7d4961990"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "5eab2fca884e26edc741b7be2fee542f657ac6342c59f6a630e57fa05b42e60b"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Cairo]]
arch = "powerpc64le"
git-tree-sha1 = "be2690b91b42b1ac9eeee6d89973e8847b8b4043"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "ca629c1b3f48f3659cca5ce953d2c9a8223da1722c122778cd61c013e7b8337e"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "95daa925da3b417338ee75ce78e16c0ac9e7cae2"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "ee07ba9ce973b47429ca32384550cee97b5ff285099f06fe56939365342f836b"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.x86_64-linux-musl.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "b1e59978a8ec7d3fcd4b2f4ec6c785b6a94a848f"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "06bc332f8efd661d7806d9a02fd40813be1dd34d568df52a4e7e38e852ecfb6e"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.x86_64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "e2e09b79f5f2f6a2df501db1b0b12755a92b1fcf"
os = "windows"

    [[Cairo.download]]
    sha256 = "d85155e3031b0d81da5320a9944821dc47e1b7f299e3c528883a44d776bb533c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.x86_64-w64-mingw32.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "4b3a9602d43b34789665f5e2a7bc09c58beaa11c"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "fb49455b7d677e01e565babd7f1f7eb062acb5991aaf9c0034a5e8faea63bf47"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.aarch64-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "6e0af76805ccb8fc090b149a6a630dcd2fed64d1"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "69340376016f0525745fc483e3dc12962d0a1576c44f1243b64f7a56aa78bdb6"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.arm-linux-gnueabihf.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "136c094a8f19fd333ea8db2e04e9c94979852574"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "347db2e09c6e5add3202f44510036ab8f15d153dcbfb6f492b2083b2fb8d72b1"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.i686-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "f5b6b5f8361b2828abe278470656ad9d9679db6c"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "8a9ab11c22dc7eefc58728c26857baed97004b5c0c5f4e8c4fada49fa5294cf4"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.arm-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "62e681247dff3af2badd6df1accea478d2ed6c86"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "222d35c12fc2d40fb7ccc501ad50d27ccc08803c5b636cc5d83a8c8fe56c6ceb"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.aarch64-linux-gnu.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "699ddc04894ca8b9dbc0b2aff7f6af7146fc7b73"
os = "windows"

    [[Cairo.download]]
    sha256 = "5993e7d41106670203614f887b684d22d456b36af7345a782a34c2146613bb64"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+1/Cairo.v1.16.0.i686-w64-mingw32.tar.gz"
