[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "53a6f28518fba80c9bdecc1fe7440ec49890511b"
os = "macos"

    [[Cairo.download]]
    sha256 = "10c142328c2fb39e7f4981f4e4adb453c9130ef0b9cdbed538906508645ca929"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.x86_64-apple-darwin14.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "7f1ee1ce7e740cd145596f85f34686c872111784"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "2ef64e2d7a57a63f02a8a8979112addd30d6fc2c27e74375a3638725fada1c49"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.i686-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "0e02ade960af91951402174aab5ef95cc5e60cdd"
os = "freebsd"

    [[Cairo.download]]
    sha256 = "8fb1e00b1024ad5d35d014edeb772718e6372718d87575bc0872004f3a6b3edc"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Cairo]]
arch = "powerpc64le"
git-tree-sha1 = "f005cb2010d6fbd1f755b53ef4f55a8adfdea97e"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "d3d65b76d885e4bd4cd400bab49a15edb70b40c068fa3c1bf82687373dc44e29"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.powerpc64le-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "8ece408d7be288849ccffbf4562ae73bd63d23a0"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "679e069cee8600e64575531c86f2c74aaea070045d902e9f9ee6826d1c04d054"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.x86_64-linux-musl.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "39eaaebe1d3e859fb6581818125f0a966fcc30c2"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "2d55845ffdc612d202fb20cbaebb0f21f6b527fbd8a881abcb55c1c45046ce4c"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.x86_64-linux-gnu.tar.gz"
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "501b655ce8fa862cfdc7706476e1893838bf8520"
os = "windows"

    [[Cairo.download]]
    sha256 = "86befe3874bde3b61bc56c63863b115133248d852f395fa7afda522a2c318fdb"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.x86_64-w64-mingw32.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "56eba5d7ceb9d3ddc2b777641b8b8c50b3b79583"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "f317f0faacd354545f0e4b30d558eb04a989494398fa5da53ebbd2f0551baac1"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.aarch64-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "8ed2cec664c8486d0a91062ac9fe2dccc152bbae"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "620badb5f74abe83e6257630f47bb14ec9d1be174651a5822276f3df4808d4de"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.arm-linux-gnueabihf.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "b811a09d8dd09e9d462b8f3827605781de5184dd"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "2081add8d1bf8fc23bd770beee41b42432518a0cf953ce6c3c376cfd24139dab"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.i686-linux-musl.tar.gz"
[[Cairo]]
arch = "armv7l"
git-tree-sha1 = "d5730e9c83f0ebec26cf85ddb59439a60f5f4a94"
libc = "musl"
os = "linux"

    [[Cairo.download]]
    sha256 = "a527ed3214b5955f3e367e28289d5fbea116fd2884a852962aaed6c259919193"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.arm-linux-musleabihf.tar.gz"
[[Cairo]]
arch = "aarch64"
git-tree-sha1 = "2d7dabb21a4e7367efdd9a3164d1345366d39823"
libc = "glibc"
os = "linux"

    [[Cairo.download]]
    sha256 = "6d1b8d91f5fc465c5cafd84d6a0c0daa3a85bb9bc194fe9b552490a9aaed330d"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.aarch64-linux-gnu.tar.gz"
[[Cairo]]
arch = "i686"
git-tree-sha1 = "77ee8ce1dd8f0e770c83ecc3ee92234c57dbf4fc"
os = "windows"

    [[Cairo.download]]
    sha256 = "cc52a2568c8179cfc222b439d5e2dc92501c66bb1dc638f51028ad18e3779667"
    url = "https://github.com/JuliaBinaryWrappers/Cairo_jll.jl/releases/download/Cairo-v1.16.0+2/Cairo.v1.16.0.i686-w64-mingw32.tar.gz"
